### ISSUE TITLE
Add support for reloading on config change

### ISSUE THREAD

**Issue by jamonation** [canonical/snap-vault#10]
Having some way to reload vault without a full restart would be very useful. For example, rotating TLS certificates without needing to unseal the vault each time. Or making any other arbitrary configuration change that vault accepts a SIGHUP reload for.

I know that this may not be directly possible with the existing snapcraft.yaml command syntax. if that's the case, I'm imaging a command wrapper of some kind that sends a SIGHUP to the child /snap/bin/vault process could work.

**Comment by javacruft** [comment]
The vault snap does not actually provide a long running service - it just provides the binary.

I agree that such a feature would be nice but its outside of what the snap delivers today.
