### ISSUE TITLE
Vault client has no access to dotfiles

### ISSUE THREAD

**Issue by Andor** [canonical/snap-vault#23]
When I'm trying to use Vault client it should be able to read/write to dotfiles like `$HOME/.vault-token`.
Also, if I will want to provide extra configuration like `export VAULT_CACERT="$HOME/.vault-ca.crt"` it will have no access to this file as well.

**Comment by Andor** [comment]
Related discussions:
https://forum.snapcraft.io/t/access-to-specific-hidden-file-path-in-users-home/6948/17
https://forum.snapcraft.io/t/the-personal-files-interface/9357
https://forum.snapcraft.io/t/syncthing-cannot-access-hidden-files-and-directories/745

**Comment by javacruft** [comment]
We can create a specific profile for vault to allow access to dotfiles - are there a specific set of paths that vault will use by default?

**Comment by gruyaume** [comment]
Closing this issue as it has been stale for a long time.
