### ISSUE TITLE
Please update snap

### ISSUE THREAD

**Issue by powersj** [canonical/snap-vault#24]
Hi! The current snap has a client that is more than a year old at this point. Can the snap please get updated to at least version 1.5?

**Comment by javacruft** [comment]
Updates and new versions for 1.2, 1.3, 1.4 and 1.5 are in flight - latest/stable will point to 1.5.x after testing.  Tracks for the others.

**Comment by powersj** [comment]
Thank you for all the updates. As these are now live, I will close this bug. Thanks again!
