### ISSUE TITLE
The stable channel still uses 1.5.9, which is long outdated.

### ISSUE THREAD

**Issue by bernhardkaindl** [canonical/snap-vault#34]
The stable channel still uses 1.5.9, which is long outdated.

For example 1.5.9 does not support the flags which the current terraform plugin uses.

Therefore scripts which make use of terraform fail if this is installed: https://github.com/standard-ai/cog

Please add some explanation why this snap is needed and why not a plain .deb is used.

After all, vault is just a single static go binary and it has a .deb package from the vendor:

See: https://www.vaultproject.io/downloads
Use:
```bash
wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
sudo apt update && sudo apt install vault
```

**Comment by javacruft** [comment]
I've had a general tidy of the tracks today; 1.10 is now the default track and I've closed the 'latest' related tracks which where obsolete.

Re your question about snaps vs debs - Snaps have different distribution semantics (tracks/channels are handy) and have security confinement policy built in.
