### ISSUE TITLE
Incorrect License Information

### ISSUE THREAD

**Issue by ssddanbrown** [canonical/snap-vault#88]
#### Describe the bug

The license found in the details for [vault on snapcraft](https://snapcraft.io/vault) show it as MPL-2.0.
The version of vault reflected is 1.15, and as far as I can tell all 1.15.x versions have been under [the Business Source License](https://github.com/hashicorp/vault/blob/v1.15.0/LICENSE), so that version won't be open source or MPL-2.0 for about 4 years.

#### To Reproduce

Go to [snapcraft page](https://snapcraft.io/vault). See license is shown as MPL-2.0.

#### Expected behavior

License should reflect that of the codebase the snap is built from (Business Source License).

#### Screenshots

<details><summary>Image</summary>
<p>

![image](https://github.com/canonical/snap-vault/assets/8343178/29c49b3b-4cdd-45cb-a8ed-5b41105cb7a8)

</p>
</details> 

#### Logs

N/A

#### Environment

- Snap revision: 1.15.x
- Snap channel: N/A
- Vault version: N/A
- Ubuntu version: N/A

#### Additional context

Apologies If I've misunderstood the setup here or licensing, or any potential custom work/maintenance that Canonical are doing. Just came across this while browsing snapcraft, so thought I'd report.

**Comment by gruyaume** [comment]
Thank you for noticing us about this @ssddanbrown , we will update the license information in the snap.
